
package org.clientservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetProduct", targetNamespace = "clientservice.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetProduct {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductList", targetNamespace = "clientservice.org", className = "org.clientservice.GetProductList")
    @ResponseWrapper(localName = "getProductListResponse", targetNamespace = "clientservice.org", className = "org.clientservice.GetProductListResponse")
    public List<String> getProductList();

}
