
package org.clientservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetProductService", targetNamespace = "clientservice.org", wsdlLocation = "http://localhost:8080/JettyApp/GetProduct?wsdl")
public class GetProductService
    extends Service
{

    private final static URL GETPRODUCTSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETPRODUCTSERVICE_EXCEPTION;
    private final static QName GETPRODUCTSERVICE_QNAME = new QName("clientservice.org", "GetProductService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/JettyApp/GetProduct?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETPRODUCTSERVICE_WSDL_LOCATION = url;
        GETPRODUCTSERVICE_EXCEPTION = e;
    }

    public GetProductService() {
        super(__getWsdlLocation(), GETPRODUCTSERVICE_QNAME);
    }

    public GetProductService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETPRODUCTSERVICE_QNAME, features);
    }

    public GetProductService(URL wsdlLocation) {
        super(wsdlLocation, GETPRODUCTSERVICE_QNAME);
    }

    public GetProductService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETPRODUCTSERVICE_QNAME, features);
    }

    public GetProductService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetProductService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetProduct
     */
    @WebEndpoint(name = "GetProductPort")
    public GetProduct getGetProductPort() {
        return super.getPort(new QName("clientservice.org", "GetProductPort"), GetProduct.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetProduct
     */
    @WebEndpoint(name = "GetProductPort")
    public GetProduct getGetProductPort(WebServiceFeature... features) {
        return super.getPort(new QName("clientservice.org", "GetProductPort"), GetProduct.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETPRODUCTSERVICE_EXCEPTION!= null) {
            throw GETPRODUCTSERVICE_EXCEPTION;
        }
        return GETPRODUCTSERVICE_WSDL_LOCATION;
    }

}
